/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlayRouteImport } from './routes/play'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RIdRouteImport } from './routes/r.$id'
import { Route as ApiScoresRouteImport } from './routes/api/scores'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiOgIdRouteImport } from './routes/api/og.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RIdRoute = RIdRouteImport.update({
  id: '/r/$id',
  path: '/r/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScoresRoute = ApiScoresRouteImport.update({
  id: '/api/scores',
  path: '/api/scores',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgIdRoute = ApiOgIdRouteImport.update({
  id: '/api/og/$id',
  path: '/api/og/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/play': typeof PlayRoute
  '/api/health': typeof ApiHealthRoute
  '/api/scores': typeof ApiScoresRoute
  '/r/$id': typeof RIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/og/$id': typeof ApiOgIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/play': typeof PlayRoute
  '/api/health': typeof ApiHealthRoute
  '/api/scores': typeof ApiScoresRoute
  '/r/$id': typeof RIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/og/$id': typeof ApiOgIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/play': typeof PlayRoute
  '/api/health': typeof ApiHealthRoute
  '/api/scores': typeof ApiScoresRoute
  '/r/$id': typeof RIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/og/$id': typeof ApiOgIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leaderboard'
    | '/play'
    | '/api/health'
    | '/api/scores'
    | '/r/$id'
    | '/api/auth/$'
    | '/api/og/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard'
    | '/play'
    | '/api/health'
    | '/api/scores'
    | '/r/$id'
    | '/api/auth/$'
    | '/api/og/$id'
  id:
    | '__root__'
    | '/'
    | '/leaderboard'
    | '/play'
    | '/api/health'
    | '/api/scores'
    | '/r/$id'
    | '/api/auth/$'
    | '/api/og/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PlayRoute: typeof PlayRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiScoresRoute: typeof ApiScoresRoute
  RIdRoute: typeof RIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOgIdRoute: typeof ApiOgIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$id': {
      id: '/r/$id'
      path: '/r/$id'
      fullPath: '/r/$id'
      preLoaderRoute: typeof RIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scores': {
      id: '/api/scores'
      path: '/api/scores'
      fullPath: '/api/scores'
      preLoaderRoute: typeof ApiScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/$id': {
      id: '/api/og/$id'
      path: '/api/og/$id'
      fullPath: '/api/og/$id'
      preLoaderRoute: typeof ApiOgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardRoute: LeaderboardRoute,
  PlayRoute: PlayRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiScoresRoute: ApiScoresRoute,
  RIdRoute: RIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOgIdRoute: ApiOgIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
